server:
  port: 8002

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:13306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: kaider

mybatis:
  type-aliases-package: com.kaider.cloud.pojo #所有pojo

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true