server:
  port: 84

spring:
  application:
    name: nacos-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719

service-url:
  nacos-user-service: http://nacos-payment-service

feign:
  sentinel:
    enabled: true
