server:
  port: 8401

spring:
  application:
    name: nacos-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'
