server:
  port: 80
spring:
  application:
    name: openfeign-order-service

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.kaider.cloud.service.PaymentFeignService: debug
